dist: bionic
os: linux
language: c
env:
    global:
        - LM_LICENSE_FILE="$TRAVIS_BUILD_DIR/tools/mwccarm/license.dat"
        - CC=gcc-8
        - CXX=g++-8
addons:
    apt:
        packages:
            - g++-8-multilib
            - linux-libc-dev
            - binutils-arm-none-eabi
            - wine32
            - wine-stable
cache:
    apt: true
install:
    # These files are only accessible from Travis CI IP Addresses to prevent piracy.
    - mkdir -p $HOME/download
    - pushd $HOME/download
    - wget http://private.martmists.com/mwccarm.zip
    - wget http://private.martmists.com/nitro.tar.gz
    - unzip mwccarm.zip
    - mv mwccarm $TRAVIS_BUILD_DIR/tools
    - tar xzf nitro.tar.gz
    - mv tools/bin $TRAVIS_BUILD_DIR/tools
    - mv include/nitro/specfiles/ARM7-TS.lcf.template $TRAVIS_BUILD_DIR/arm7
    - mv include/nitro/specfiles/ARM9-TS.lcf.template $TRAVIS_BUILD_DIR/arm9
    - popd
    - for fl in files/msgdata/msg/*.txt; do iconv -f utf-16 $fl > tmp.txt && mv tmp.txt $fl; done || true

script:
    - travis_retry make
    - travis_retry make pearl

notifications:
  email: false

after_success:
    - .travis/calcrom/webhook.sh pokediamond
